name: Manual2

on:
  workflow_dispatch:

jobs:
  printenv:
    runs-on: ubuntu-latest
    env:
      password: SuperSecretPassword
    steps:
      - run: echo "::add-mask::${password}"
      - run: echo "${password}"