name: Manual

on:
  workflow_dispatch:
    inputs:
      greeting:
        type: choice 
        options:
          - Hello
          - Hi
          - Good Afternoon
        required: true
        description: A cheerful word

env:
  BRANCH: main
  ANIMAL: ${{vars.ANIMAL}}

jobs:
  printenv:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "$BRANCH"
      - run: echo "$ACTOR"
      - run: echo "$ANIMAL"
      - run: echo "${{inputs.greeting}}"
