name: Manual

on:
  workflow_dispatch:
    inputs:
      greeting:
        type: choice 
        options:
          - Hello
          - Hi
          - Good Afternoon
        required: true
        description: A cheerful word

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.actor}}"
      - run: echo "${{inputs.greeting}}"
